server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
  #配置版本号的内容
    instance-id:  ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    metadata-map:
      other: custom
      it: other


feign:
  hystrix:
    enabled: true